### ISSUE TITLE
How to handle inter-process comunication with ambiorix?

### ISSUE THREAD

**Issue by JulioCollazos64** [ambiorix-web/ambiorix#80]
Hello there! 
Thanks for this wonderful package, it works great with htmx.

One thing I'd like to implement in an app is to display some kind of progress as computation occurs. I searched some related topics and found the `ipc` library, as I read its [docs](https://www.theoj.org/joss-papers/joss.00988/10.21105.joss.00988.pdf) I discovered that inter-process communication is needed for this kind of functionality 

Below I have a simple app which should resembles a progress bar (User clicks button, async process starts and new UI show the progress `value`), but nothing happens and the value is stuck at zero.

```r
library(future)
library(ambiorix)
library(ipc)
library(htmltools)
plan(multisession)
app <- Ambiorix$new()
value <- 0
q <- queue()
app$get("/", \(req,res){
  tags$button(
    `hx-post` = "/end1",
    "Begin progress"
  ) |> 
    as.character() |> 
    HTML() -> var_1
  res$render("temp.html", list(html_1 = var_1))
})
app$post("/end1", \(req,res){
  futuro_1 <- future({
    for(i in 1:5){
      Sys.sleep(3)
      q$producer$fireEval({
        # print(index)
        value <- index
        value
  
      }, list(index=i))
   }
  })
  futuro_1
  q$consumer$start()
  div(
      `hx-get` = "/getvals",
      `hx-trigger` = "every 2s",
      "Creating Archive"
    ) |> 
    as.character() |> 
    HTML() -> var_2
  res$send(var_2)
})

app$get("/getvals", \(req,res){
  # value
  res$send(as.character(value))
})

app$start()

```
`temp.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://unpkg.com/htmx.org@2.0.3" integrity="sha384-0895/pl2MU10Hqc6jd4RvrthNlDiE9U1tWmX7WRESftEDRosgxNsQG/Ze9YMRzHq" crossorigin="anonymous"></script>
</head>
<body>
    [% html_1 %]
</body>
</html>
```
Is this possible using ambiorix? Maybe another approach?

**Comment by kennedymwavu** [comment]
hello @JulioCollazos64,
great question! i am not familiar with `{ipc}` but:
1. when using `{future}` with `plan(multisession)`, the R expression is evaluated in a different R session. this means that any local & global variables you had are copied over to the new R session. so any changes to the variables only happens in that new session, not the old one. that is why the value is stuck at zero.
from the docs of `{future}`:
    > When a future is constructed, global variables are identified. For asynchronous evaluation, globals are exported to the R process/session that will be evaluating the future expression. For sequential futures with lazy evaluation (lazy = TRUE), globals are “frozen” (cloned to a local environment of the future). Also, in order to protect against exporting too large objects by mistake, there is a built-in assertion that the total size of all globals is less than a given threshold (controllable via an option, cf. [help("future.options")](https://future.futureverse.org/reference/future.options.html)). If the threshold is exceeded, an informative error is thrown.

2. in that light, i believe storing the task progress in a database is the best approach here. a temporary SQLite db is perfect for that. it can be initialized when the app starts & deleted when the app stops by adding an [`app$on_stop`](https://ambiorix.dev/docs/ambiorix/stop/#on-stop) callback. when the async process starts, you'd generate a unique id for its progress, which htmx would then use to poll. as the computation continues, you'd keep on updating the db table, and when htmx polls again, it'd get the current progress value. when the async process is done, you can remove that db record because it will no longer be needed.

i will work on a reprex and link it here.

**Comment by kennedymwavu** [comment]
checkout the reprex here: [show-progress-async](https://github.com/kennedymwavu/ambiorix-htmx/tree/main/show-progress-async)

here's a demo of the same:

https://github.com/user-attachments/assets/cb917749-fdf1-4ccf-9b74-9ed84937b78f

**Comment by kennedymwavu** [comment]
leaving this here for future reference: adding an `id` attribute on the progress bar div makes htmx smoothly transition btwn requests by settling the style attribute into its new value. coupled with a css transition, the visual change will seem continuous rather than jumpy.

```css
.progress-bar {
  transition: width .6s ease;
}
```

i've updated [the reprex](https://github.com/kennedymwavu/ambiorix-htmx/tree/main/show-progress-async) to include all that.

here's a demo of the update:


https://github.com/user-attachments/assets/bb60061b-c67b-4415-ba27-8a5f0c2cda56
