### ISSUE TITLE
improve route parameter handling and error reporting

### ISSUE THREAD

**Issue by kennedymwavu** [ambiorix-web/ambiorix#81]
## description

when defining routes with overlapping patterns, the order of definition matters.

say we have these 2 endpoints and their respective handlers:
- `/app/:id` -> `app_get`
- `/app/:id/hello` -> `app_hello`

the expected behaviour would be:
- if you define `/app/:id` before `/app/:id/hello`, requests to `/app/:id/hello` would be handled by `app_get` because `/:id` will match anything after `/app/`.
- if you define `/app/:id/hello` **before** `/app/:id`, it should work well because a more specific route will be matched first and then `/app/:id` would handle any other requests.

## the issue

currently in ambiorix when you define `/app/:id` first, visiting `/app/:id/hello` *silently* returns a 500 to the client with:

```
ERROR: subscript out of bounds
```

this error:
- escapes the global error handler, making debugging difficult
- fails to provide clear feedback about what went wrong

## reprex

```r
library(ambiorix)
library(htmltools)

home_get <- \(req, res) {
  html <- tags$h3("hello, world!")
  res$send(html)
}

app_get <- \(req, res) {
  html <- tags$h3("you're visiting app with id:", req$params$id)
  res$send(html)
}

app_hello <- \(req, res) {
  msg <- sprintf(
    "app with id '%s' says hello",
    req$params$id
  )
  html <- tags$h3(msg)
  res$send(html)
}

error_handler <- \(req, res, error){
  res$status(500L)
  res$send("There was a server error :(")
}

app <- Ambiorix$new(port = 5000L)$
  set_error(error_handler)$
  get("/", home_get)$
  get("/app/:id", app_get)$ # MUST be defined AFTER '/app/:id/hello'
  get("/app/:id/hello", app_hello)

app$start()
```

## question

what would be the best way to handle this?
1. handling `/app/:id/hello` correctly (based on route order)?
2. throwing a clearer, louder error?
3. something else maybe?

would like to hear your thoughts on this @JohnCoene

**Comment by JohnCoene** [comment]
I'll take a look, I don't think the suggested behaviour is correct though. It should match `/:id/hello` before `/:id` regardless of the order in which they are defined. Also think of the following route `/app/xxx`, and `/app/xx` you want to match the first before the second.

Pattern matching in these frameworks is both an art and a science, see [slighe](https://github.com/ambiorix-web/slighe), it uses a Javascript library to transform the path to a sensible regular expression so that they should match correctly.

In ambiorix I took a shortcut because the above is a lot of work, ambiorix simply matches the longest route first hence the reordering of the routes, see https://github.com/ambiorix-web/ambiorix/blob/459a5b5efa4994f8dfbf95856ddfe34f5bf054c9/R/routing.R#L440 

I'll try to nail down the bug on this subscript out of bounds, do you have any clue where it occurs?

**Comment by JohnCoene** [comment]
Can you try `fix/81-routing` and let me know if it works as intended?
